### PR TITLE
Ux destinations

### PR DESCRIPTION
**Pull request by claratee**
currently getting error on viewing listings without timeframe. fix before merge

### CODE REVIEW

**Comment by claratee** [comment]
I didn't realise my comments and pull requests were going on your master project thought I was limited to my fork, sorry!  I do want to merge but not ready yet.

**Comment by robf** [comment]
Thanks, claratee, these will be useful contributions. 

However, due to the dependencies on out of date Pear libraries and PHP versions and other issues, Chris and myself are currently developing a complete rewrite of Local Exchange, initially just for the Falmouth (and other Cornish) LETS groups. It will have all the functionality of Local Exchange as well as its own theming and CMS system

Once its working for the Falmouth group we'll be putting it on github for public use to enable further forking, adaptation and development (including by LETSlink UK), but in the meantime if you'd like to get involved at an early stage, please let us know. We'd particularly welcome expertise in CSS and theme design for the front end.

Best,

Rob

**Comment by claratee** [comment]
Hi Rob and Chris,
I'd be happy to help. It would be great to see localexchange move away from
old php and PEAR dependencies. I agree that it's work that is necessary for
longevity, security and stability.

My specialism is UX and css, would love to get LETS trading working nicely
on phones and tablets, and also build a better user experience into your
info page editing functionality.

If it's OK with you, I'll continue with what I am doing on my fork - kinda
eager to get some improvements into our own CamLETS system and extricate
ourselves from LETSLinkUK (it's not been a particularly easy relationship)
- and trust there is a path to migrate with some of the work I'm doing.
I've had a few false starts with this, you may remember I got in touch a
few few years ago, but I think I was using the wrong fork (this one is a
lot more complete and closer to what we have with LETSLinkUK), investigated
alternative LETS software, but came back to your version of LocalExchange
as it has much of what we need and represents the least painful transition
for our membership...

Many thanks for getting in touch so quickly. I'll continue tracking on
github and send you a link to the demo when it's in a stable state.

Clara

**Comment by robf** [comment]
That's great, Clara. UX and CSS skills will be really useful.

Yes, no problem at all with you using the Local Exchange code as you wish - all versions are after all GPL!

Its also similar to the version used by LLUK - we developed it early on with them, but they tend to add undocumented hacks whereas we've tried to focus on fixing bugs and they haven't collaborated with us since on Git (or on Source Forge when we maintained it there)

Re Mutual Credit  (the new software, renamed as its a complete rewrite):

We want a basic version without feature-creep working and tested for the Falmouth group before we make it public or released to the wider LETS community (including LLUK).

Yes, its already possible to import the trading and membership data from Local Exchange to Mutual Credit which will also be GPL once completed. 

Do get in touch via [the contact page on my website](http://rofo.co.uk/contact/) so I have an email address for you and can invite you to our Trello and Slack pages for the new project. 

Also happy to discuss on the phone if you wish? Number is on above link

**Comment by claratee** [comment]
Hi Rob,
I'd like to, but your mailer is not working for me - tried on Chrome and
Firefox on my Mac with valid fields.

*ERROR:* Sorry, there was an error. Please be sure JavaScript and Cookies
are enabled in your browser and try again.

Mutual Credit - do invite me to collaborate on trello and slack, sounds
good. Contribution will have to fit around work and family life. You can
connect on skype, I like putting faces to names - search for my details:
claratodd cambridge clara_todd@hotmail.com.

**Pull request closed without merging**
